# Generated by Django 5.0.2 on 2024-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
