# Generated by Django 5.0.2 on 2024-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0003_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
