# Generated by Django 5.0.2 on 2024-03-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0005_about_blog_contact_product_comment_single_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='products',
        ),
    ]
