# Generated by Django 5.0.2 on 2024-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0006_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
