# Generated by Django 5.0.2 on 2024-03-23 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0010_rename_sender_name_message_author_message_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='CommentForm',
        ),
    ]
