# Generated by Django 5.0.2 on 2024-03-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0011_rename_message_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
