# Generated by Django 5.0.2 on 2024-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0013_rename_comment_message_alter_destination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('special_offer', models.BooleanField(default=False)),
            ],
        ),
    ]
