# Generated by Django 5.0.2 on 2024-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kampalaBlog', '0014_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='special_offer',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
